name: NxBrokenItems
version: '1.0.1'
main: dev.fluffyworld.nxbrokenitems.NxBrokenItems
author: MasterN
description: Plugin that helps in restoring broken items
api-version: '1.21'
commands:
  nxbrokenitems:
    description: Restore or reload broken items
    aliases:
      - nb
permissions:
  nxbrokenitems.restore:
    description: Allows the player to restore broken items
    default: true
  nxbrokenitems.delete:
    description: Allows the player to delete broken items
    default: true
  nxbrokenitems.reload:
    description: Allows the player to reload the plugin configuration
    default: op
depend: [Vault, PlaceholderAPI]